spring.application.name=product
spring.datasource.url=jdbc:mysql://localhost:3306/dwb2027
spring.datasource.username=root
spring.datasource.password=XxContasena6393xX
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver